export const beers = {
  meta: {
    code: 200,
    response_time: {
      time: 0.236,
      measure: 'seconds',
    },
    init_time: {
      time: 0,
      measure: 'seconds',
    },
  },
  notifications: [],
  response: {
    total_count: 871,
    dates: {
      first_checkin_date: 'Fri, 07 Jun 2019 22:41:02 +0000',
      start_date: false,
      end_date: false,
      tzOffset: '0',
    },
    is_search: false,
    sort: false,
    type_id: false,
    country_id: false,
    brewery_id: false,
    rating_score: false,
    region_id: false,
    container_id: false,
    is_multi_type: false,
    beers: {
      count: 25,
      items: [
        {
          first_checkin_id: 1099015485,
          first_created_at: 'Sun, 14 Nov 2021 22:02:31 +0300',
          recent_checkin_id: 1099015485,
          recent_created_at: 'Sun, 14 Nov 2021 22:02:31 +0300',
          recent_created_at_timezone: '3',
          rating_score: 3.5,
          user_auth_rating_score: 0,
          first_had: 'Sun, 14 Nov 2021 22:02:31 +0300',
          count: 1,
          beer: {
            bid: 689782,
            beer_name: 'Pyder',
            beer_label:
              'https://untappd.akamaized.net/site/beer_logos/beer-689782_344f2_sm.jpeg',
            beer_abv: 5,
            beer_ibu: 0,
            beer_slug: 'gwatkin-cider-farm-pyder',
            beer_style: 'Cider - Perry',
            beer_description:
              'Pyder is the Original Pear Cider made from a blend of the best apples and pears grown in the county of Herefordshire. Blended and balanced to give the best taste of these two great fruits. Sweet, Best served chilled.',
            created_at: 'Fri, 23 May 2014 19:08:18 +0000',
            rating_score: 3.51513,
            rating_count: 238,
            has_had: false,
          },
          brewery: {
            brewery_id: 19550,
            brewery_name: 'Gwatkin Cider Co Ltd',
            brewery_slug: 'gwatkin-cider-co-ltd',
            brewery_page_url: '/GwatkinCiderFarm',
            brewery_type: 'Cidery',
            brewery_label:
              'https://untappd.akamaized.net/site/brewery_logos/brewery-GwatkinsCiderFarm_19550_11993.jpeg',
            country_name: 'England',
            contact: {
              twitter: 'GwatkinCider',
              facebook:
                'https://www.facebook.com/pages/Gwatkin-Cider/138521139506859',
              instagram: '',
              url: 'http://www.gwatkincider.co.uk/',
            },
            location: {
              brewery_city: 'Abbey Dore',
              brewery_state: 'Herefordshire',
              lat: 52.0015984,
              lng: -2.90836,
            },
            brewery_active: 1,
          },
        },
        {
          first_checkin_id: 1098774353,
          first_created_at: 'Sun, 14 Nov 2021 04:27:49 +0300',
          recent_checkin_id: 1098774353,
          recent_created_at: 'Sun, 14 Nov 2021 04:27:49 +0300',
          recent_created_at_timezone: '3',
          rating_score: 2.5,
          user_auth_rating_score: 0,
          first_had: 'Sun, 14 Nov 2021 04:27:49 +0300',
          count: 1,
          beer: {
            bid: 229044,
            beer_name: 'Hamovniki Venskoe (Хамовники Венское)',
            beer_label:
              'https://untappd.akamaized.net/site/beer_logos/beer-229044_24214_sm.jpeg',
            beer_abv: 4.5,
            beer_ibu: 21,
            beer_slug:
              'moscow-brewing-company-moskovskaya-pivovarennaya-kompaniya-hamovniki-venskoe-hamovniki-venskoe',
            beer_style: 'Lager - Vienna',
            beer_description:
              '«Хамовники Венское» сварено с использованием специальных солодов, традиционных для стиля «Венский лагер». Это солода: светлый, венский, «Караред» и карамельный. При производстве применяется только тонко-ароматный благородный немецкий хмель: «Сапфир» и «Теттнангер», что придаёт пиву нежный цветочный аромат и очень мягкую горечь.',
            created_at: 'Thu, 13 Sep 2012 17:42:30 +0000',
            rating_score: 3.14052,
            rating_count: 10302,
            has_had: false,
          },
          brewery: {
            brewery_id: 7165,
            brewery_name:
              'Moscow Brewing Company (Московская Пивоваренная Компания)',
            brewery_slug:
              'moscow-brewing-company-moskovskaya-pivovarennaya-kompaniya',
            brewery_page_url: '/Moscow_Brewing_Company___',
            brewery_type: 'Macro Brewery',
            brewery_label:
              'https://untappd.akamaized.net/site/brewery_logos/brewery-MoskovskayaPivovarennayaKompaniya_7165.jpeg',
            country_name: 'Russia',
            contact: {
              twitter: 'mosbrew',
              facebook: 'http://www.facebook.com/BEERandTALK',
              instagram: '',
              url: 'http://www.mosbrew.ru',
            },
            location: {
              brewery_city: 'Mytishchi',
              brewery_state: 'Московская область',
              lat: 55.9197998,
              lng: 37.7654991,
            },
            brewery_active: 1,
          },
        },
        {
          first_checkin_id: 1098586143,
          first_created_at: 'Sun, 14 Nov 2021 00:33:10 +0300',
          recent_checkin_id: 1098586143,
          recent_created_at: 'Sun, 14 Nov 2021 00:33:10 +0300',
          recent_created_at_timezone: '3',
          rating_score: 4,
          user_auth_rating_score: 0,
          first_had: 'Sun, 14 Nov 2021 00:33:10 +0300',
          count: 1,
          beer: {
            bid: 4536116,
            beer_name: 'Strudel Wunderbar',
            beer_label:
              'https://untappd.akamaized.net/site/beer_logos/beer-4536116_2bbd1_sm.jpeg',
            beer_abv: 5.5,
            beer_ibu: 0,
            beer_slug: 'cosmic-city-strudel-wunderbar',
            beer_style: 'Mead - Melomel',
            beer_description:
              'Изысканный смузимель со вкусом и ароматом знаменитых штруделей от Фрау Марты. Традиционный автрийский штрудель – это рулет из тонкого бездрожжевого вытяжного теста с яблочной начинкой.\r\n\r\nВзяв за основу классический рецепт из австрийского настенного календаря 1982 года, мы соединили яблоки, немного теста, сухую медовуху и посыпали наш десертный напиток корицей.\r\n\r\nИ запомните основной секрет Фрау Марты. Штрудель - это совсем не «Шарлотка».',
            created_at: 'Wed, 06 Oct 2021 15:49:04 +0000',
            rating_score: 4.18144,
            rating_count: 132,
            has_had: false,
          },
          brewery: {
            brewery_id: 89993,
            brewery_name: 'Cosmic City',
            brewery_slug: 'cosmic-city',
            brewery_page_url: '/CosmicCityBrew',
            brewery_type: 'Contract Brewery',
            brewery_label:
              'https://untappd.akamaized.net/site/brewery_logos/brewery-89993_3bdc9.jpeg',
            country_name: 'Russia',
            contact: {
              twitter: 'settarov',
              facebook: 'https://www.facebook.com/cosmiccitybrew',
              instagram: 'cosmiccitybrew',
              url: '',
            },
            location: {
              brewery_city: 'Korolyov',
              brewery_state: 'Московская область',
              lat: 55.9317017,
              lng: 37.8518982,
            },
            brewery_active: 1,
          },
        },
        {
          first_checkin_id: 1098584741,
          first_created_at: 'Sun, 14 Nov 2021 00:31:50 +0300',
          recent_checkin_id: 1098584741,
          recent_created_at: 'Sun, 14 Nov 2021 00:31:50 +0300',
          recent_created_at_timezone: '3',
          rating_score: 3.75,
          user_auth_rating_score: 0,
          first_had: 'Sun, 14 Nov 2021 00:31:50 +0300',
          count: 1,
          beer: {
            bid: 4575970,
            beer_name: 'Pump King En Regalia - 2021',
            beer_label:
              'https://untappd.akamaized.net/site/assets/images/temp/badge-beer-default.png',
            beer_abv: 6,
            beer_ibu: 0,
            beer_slug: 'cosmic-city-pump-king-en-regalia-2021',
            beer_style: 'Mead - Other',
            beer_description:
              'Королевский смузимид, с добавлением сладкой тыквы, сочного персика, карамели и арахиса. Осенний и тыквенный, танцующий в полном одиночестве на ковре из жëлтых листьев. Встречайте с почестями только в Share House. ',
            created_at: 'Tue, 02 Nov 2021 09:50:10 +0000',
            rating_score: 4.06364,
            rating_count: 33,
            has_had: false,
          },
          brewery: {
            brewery_id: 89993,
            brewery_name: 'Cosmic City',
            brewery_slug: 'cosmic-city',
            brewery_page_url: '/CosmicCityBrew',
            brewery_type: 'Contract Brewery',
            brewery_label:
              'https://untappd.akamaized.net/site/brewery_logos/brewery-89993_3bdc9.jpeg',
            country_name: 'Russia',
            contact: {
              twitter: 'settarov',
              facebook: 'https://www.facebook.com/cosmiccitybrew',
              instagram: 'cosmiccitybrew',
              url: '',
            },
            location: {
              brewery_city: 'Korolyov',
              brewery_state: 'Московская область',
              lat: 55.9317017,
              lng: 37.8518982,
            },
            brewery_active: 1,
          },
        },
        {
          first_checkin_id: 1098561398,
          first_created_at: 'Sun, 14 Nov 2021 00:10:16 +0300',
          recent_checkin_id: 1098561398,
          recent_created_at: 'Sun, 14 Nov 2021 00:10:16 +0300',
          recent_created_at_timezone: '3',
          rating_score: 3.5,
          user_auth_rating_score: 0,
          first_had: 'Sun, 14 Nov 2021 00:10:16 +0300',
          count: 1,
          beer: {
            bid: 4504289,
            beer_name: 'Compact',
            beer_label:
              'https://untappd.akamaized.net/site/beer_logos/beer-4504289_dd115_sm.jpeg',
            beer_abv: 6,
            beer_ibu: 0,
            beer_slug: 'red-button-brewery-compact',
            beer_style: 'IPA - Sour',
            beer_description:
              '(CMC) Columbus x Mosaic x Citra Dry Hop Sour ipa ',
            created_at: 'Tue, 14 Sep 2021 14:21:55 +0000',
            rating_score: 3.92917,
            rating_count: 300,
            has_had: false,
          },
          brewery: {
            brewery_id: 241689,
            brewery_name: 'Red Button Brewery',
            brewery_slug: 'red-button-brewery',
            brewery_page_url: '/RedButtonBrewery',
            brewery_type: 'Micro Brewery',
            brewery_label:
              'https://untappd.akamaized.net/site/brewery_logos/brewery-241689_ac322.jpeg',
            country_name: 'Russia',
            contact: {
              twitter: '',
              facebook: 'https://www.facebook.com/redbuttonbrewery',
              instagram: 'redbuttonbrew',
              url: 'https://www.redbutton.beer',
            },
            location: {
              brewery_city: 'Moscow',
              brewery_state: 'Москва',
              lat: 55.7368011,
              lng: 37.7234993,
            },
            brewery_active: 1,
          },
        },
        {
          first_checkin_id: 1098544143,
          first_created_at: 'Sat, 13 Nov 2021 23:54:57 +0300',
          recent_checkin_id: 1098544143,
          recent_created_at: 'Sat, 13 Nov 2021 23:54:57 +0300',
          recent_created_at_timezone: '3',
          rating_score: 3.75,
          user_auth_rating_score: 0,
          first_had: 'Sat, 13 Nov 2021 23:54:57 +0300',
          count: 1,
          beer: {
            bid: 4534490,
            beer_name: 'Great Benefit',
            beer_label:
              'https://untappd.akamaized.net/site/beer_logos/beer-4534490_4f08c_sm.jpeg',
            beer_abv: 5.9,
            beer_ibu: 0,
            beer_slug: 'mitra-brewing-co-great-benefit',
            beer_style: 'Sour - Smoothie / Pastry',
            beer_description:
              'Tooth breaker pastry sour ale with peach, almond and lactose.\r\n\r\nOne of new reborn Mitra experiment. \r\n\r\nHurry Up!\r\n\r\nGreat Benefit\r\n\r\nПерсик х Миндаль х Лактоза\r\n\r\nТот самый пирог, которая жена собирает своему мужу - корпоративному самураю, на работу в каменных джунглях\r\n\r\nСмузи-лайк десертный эль с персиком, миндалём и лактозой, новая митра, новый вкус',
            created_at: 'Mon, 04 Oct 2021 20:37:11 +0000',
            rating_score: 4.16143,
            rating_count: 70,
            has_had: false,
          },
          brewery: {
            brewery_id: 478818,
            brewery_name: 'Mitra Brewing Co.',
            brewery_slug: 'mitra-brewing-co',
            brewery_page_url: '/MitraBrewing',
            brewery_type: 'Contract Brewery',
            brewery_label:
              'https://untappd.akamaized.net/site/brewery_logos/brewery-478818_634a7.jpeg',
            country_name: 'Russia',
            contact: {
              twitter: '',
              facebook: 'https://facebook.com/mitrabrewingco/',
              instagram: 'mitrabrewingco',
              url: '',
            },
            location: {
              brewery_city: '',
              brewery_state: '',
              lat: 0,
              lng: 0,
            },
            brewery_active: 1,
          },
        },
        {
          first_checkin_id: 1098534846,
          first_created_at: 'Sat, 13 Nov 2021 23:46:51 +0300',
          recent_checkin_id: 1098534846,
          recent_created_at: 'Sat, 13 Nov 2021 23:46:51 +0300',
          recent_created_at_timezone: '3',
          rating_score: 4,
          user_auth_rating_score: 0,
          first_had: 'Sat, 13 Nov 2021 23:46:51 +0300',
          count: 1,
          beer: {
            bid: 4587193,
            beer_name: 'Sarcasmotron #5',
            beer_label:
              'https://untappd.akamaized.net/site/assets/images/temp/badge-beer-default.png',
            beer_abv: 15,
            beer_ibu: 0,
            beer_slug: 'share-house-sarcasmotron-5',
            beer_style: 'Mead - Other',
            beer_description:
              'Продолжаем Эру Сарказмотрона! Хрустальная мечта уставшего биргика сверкающая на стойке в том самом барчике, где делят бутылки, горести и радости.\r\n\r\nВерсия пятая: с хреном, чёрной редькой и имбирём. \r\n',
            created_at: 'Wed, 10 Nov 2021 14:25:15 +0000',
            rating_score: 4.05909,
            rating_count: 33,
            has_had: false,
          },
          brewery: {
            brewery_id: 424520,
            brewery_name: 'Share House',
            brewery_slug: 'share-house',
            brewery_page_url: '/Share-House',
            brewery_type: 'Brew Pub',
            brewery_label:
              'https://untappd.akamaized.net/site/brewery_logos/brewery-424520_1b13b.jpeg',
            country_name: 'Russia',
            contact: {
              twitter: '',
              facebook: 'https://www.facebook.com/sharehousebar/',
              instagram: 'sharehousebar',
              url: '',
            },
            location: {
              brewery_city: 'Moscow',
              brewery_state: 'Москва',
              lat: 55.7706985,
              lng: 37.5969009,
            },
            brewery_active: 1,
          },
        },
        {
          first_checkin_id: 1098533615,
          first_created_at: 'Sat, 13 Nov 2021 23:45:46 +0300',
          recent_checkin_id: 1098533615,
          recent_created_at: 'Sat, 13 Nov 2021 23:45:46 +0300',
          recent_created_at_timezone: '3',
          rating_score: 3.75,
          user_auth_rating_score: 0,
          first_had: 'Sat, 13 Nov 2021 23:45:46 +0300',
          count: 1,
          beer: {
            bid: 4212159,
            beer_name: 'Templars  Normandy Cider',
            beer_label:
              'https://untappd.akamaized.net/site/assets/images/temp/badge-beer-default.png',
            beer_abv: 6,
            beer_ibu: 0,
            beer_slug: 'monsieur-adam-bland-siret-templars-normandy-cider',
            beer_style: 'Cider - Dry',
            beer_description: 'Dry Normand Cidre',
            created_at: 'Mon, 08 Mar 2021 19:41:38 +0000',
            rating_score: 3.61176,
            rating_count: 34,
            has_had: false,
          },
          brewery: {
            brewery_id: 491541,
            brewery_name: 'Monsieur Adam Bland Siret',
            brewery_slug: 'monsieur-adam-bland-siret',
            brewery_page_url: '/w/monsieur-adam-bland-siret/491541',
            brewery_type: 'Cidery',
            brewery_label:
              'https://untappd.akamaized.net/site/assets/images/temp/badge-brewery-default.png',
            country_name: 'France',
            contact: {
              twitter: '',
              facebook: '',
              instagram: '',
              url: '',
            },
            location: {
              brewery_city: '',
              brewery_state: '',
              lat: 0,
              lng: 0,
            },
            brewery_active: 1,
          },
        },
        {
          first_checkin_id: 1098470951,
          first_created_at: 'Sat, 13 Nov 2021 22:51:59 +0300',
          recent_checkin_id: 1098470951,
          recent_created_at: 'Sat, 13 Nov 2021 22:51:59 +0300',
          recent_created_at_timezone: '3',
          rating_score: 3.75,
          user_auth_rating_score: 0,
          first_had: 'Sat, 13 Nov 2021 22:51:59 +0300',
          count: 1,
          beer: {
            bid: 3823012,
            beer_name: 'Ribayu Sidra Natural Extra Selección',
            beer_label:
              'https://untappd.akamaized.net/site/beer_logos/beer-3823012_73570_sm.jpeg',
            beer_abv: 6.5,
            beer_ibu: 0,
            beer_slug: 'guzman-riestra-ribayu-sidra-natural-extra-seleccion',
            beer_style: 'Cider - Traditional / Apfelwein',
            beer_description: '',
            created_at: 'Fri, 12 Jun 2020 11:34:23 +0000',
            rating_score: 4.14423,
            rating_count: 26,
            has_had: false,
          },
          brewery: {
            brewery_id: 136670,
            brewery_name: 'Guzman Riestra',
            brewery_slug: 'guzman-riestra',
            brewery_page_url: '/w/guzman-riestra/136670',
            brewery_type: 'Cidery',
            brewery_label:
              'https://untappd.akamaized.net/site/brewery_logos/brewery-136670_b2d3b.jpeg',
            country_name: 'Spain',
            contact: {
              twitter: '',
              facebook: '',
              instagram: '',
              url: 'https://www.sidrariestra.com',
            },
            location: {
              brewery_city: '',
              brewery_state: '',
              lat: 0,
              lng: 0,
            },
            brewery_active: 1,
          },
        },
        {
          first_checkin_id: 1098449218,
          first_created_at: 'Sat, 13 Nov 2021 22:32:44 +0300',
          recent_checkin_id: 1098449218,
          recent_created_at: 'Sat, 13 Nov 2021 22:32:44 +0300',
          recent_created_at_timezone: '3',
          rating_score: 3.75,
          user_auth_rating_score: 0,
          first_had: 'Sat, 13 Nov 2021 22:32:44 +0300',
          count: 1,
          beer: {
            bid: 4518198,
            beer_name: 'Colour Emulsion',
            beer_label:
              'https://untappd.akamaized.net/site/beer_logos/beer-4518198_76325_sm.jpeg',
            beer_abv: 6,
            beer_ibu: 0,
            beer_slug: 'big-village-brewery-colour-emulsion',
            beer_style: 'Sour - Fruited',
            beer_description:
              'Мультивитаминный сауэр эль сброженный по технологии sour fermentation нашим домашним лактоблендом и заполненный ягодами клубники и соком красного апельсина.',
            created_at: 'Fri, 24 Sep 2021 11:13:43 +0000',
            rating_score: 3.71927,
            rating_count: 423,
            has_had: false,
          },
          brewery: {
            brewery_id: 210563,
            brewery_name: 'Big Village Brewery',
            brewery_slug: 'big-village-brewery',
            brewery_page_url: '/BVBrewery',
            brewery_type: 'Micro Brewery',
            brewery_label:
              'https://untappd.akamaized.net/site/brewery_logos/brewery-210563_22887.jpeg',
            country_name: 'Russia',
            contact: {
              twitter: '',
              facebook: 'https://facebook.com/bigvillagebrewery',
              instagram: 'big_village_brew',
              url: 'https://vk.com/bigvillage',
            },
            location: {
              brewery_city: 'Krasnodar',
              brewery_state: 'Краснодарский край',
              lat: 45.0261993,
              lng: 39.0460014,
            },
            brewery_active: 1,
          },
        },
        {
          first_checkin_id: 1098445001,
          first_created_at: 'Sat, 13 Nov 2021 22:29:05 +0300',
          recent_checkin_id: 1098445001,
          recent_created_at: 'Sat, 13 Nov 2021 22:29:05 +0300',
          recent_created_at_timezone: '3',
          rating_score: 3.75,
          user_auth_rating_score: 0,
          first_had: 'Sat, 13 Nov 2021 22:29:05 +0300',
          count: 1,
          beer: {
            bid: 4166489,
            beer_name: 'FRUE',
            beer_label:
              'https://untappd.akamaized.net/site/beer_logos/beer-4166489_73de1_sm.jpeg',
            beer_abv: 5,
            beer_ibu: 0,
            beer_slug: 'oh-no-cidrerie-frue',
            beer_style: 'Cider - Perry',
            beer_description: ' Peach THICK Poire ',
            created_at: 'Thu, 04 Feb 2021 13:24:32 +0000',
            rating_score: 4.04303,
            rating_count: 294,
            has_had: false,
          },
          brewery: {
            brewery_id: 450190,
            brewery_name: 'Oh No Cidrerie',
            brewery_slug: 'oh-no-cidrerie',
            brewery_page_url: '/OhNoCidrerie',
            brewery_type: 'Cidery',
            brewery_label:
              'https://untappd.akamaized.net/site/brewery_logos/brewery-450190_68b49.jpeg',
            country_name: 'Russia',
            contact: {
              twitter: '',
              facebook: '',
              instagram: '',
              url: '',
            },
            location: {
              brewery_city: 'Moscow',
              brewery_state: 'Москва',
              lat: 55.7557983,
              lng: 37.6172981,
            },
            brewery_active: 1,
          },
        },
        {
          first_checkin_id: 1098443115,
          first_created_at: 'Sat, 13 Nov 2021 22:27:26 +0300',
          recent_checkin_id: 1098443115,
          recent_created_at: 'Sat, 13 Nov 2021 22:27:26 +0300',
          recent_created_at_timezone: '3',
          rating_score: 3.5,
          user_auth_rating_score: 0,
          first_had: 'Sat, 13 Nov 2021 22:27:26 +0300',
          count: 1,
          beer: {
            bid: 4569402,
            beer_name: 'Banoffee',
            beer_label:
              'https://untappd.akamaized.net/site/beer_logos/beer-4569402_fa737_sm.jpeg',
            beer_abv: 5.9,
            beer_ibu: 9,
            beer_slug: 'rising-moon-brewery-banoffee',
            beer_style: 'Sour - Fruited',
            beer_description:
              'Банан, карамель и соль! И всё это в пиве под названием Banoffee! У нашего пивовара и у команды было веселое настроение, вот так и появилось наше творение. Надеемся, что частичка отличного настроения перейдёт и Вам, ведь бананы всегда подразумевают пляж и солнце.   ',
            created_at: 'Fri, 29 Oct 2021 08:08:38 +0000',
            rating_score: 3.875,
            rating_count: 38,
            has_had: false,
          },
          brewery: {
            brewery_id: 337614,
            brewery_name: 'Rising Moon Brewery',
            brewery_slug: 'rising-moon-brewery',
            brewery_page_url: '/RMBrewery',
            brewery_type: 'Micro Brewery',
            brewery_label:
              'https://untappd.akamaized.net/site/brewery_logos/brewery-337614_a4dd4.jpeg',
            country_name: 'Russia',
            contact: {
              twitter: '',
              facebook: '',
              instagram: 'risingmoonbrewery.ru',
              url: 'http://www.rmbrew.ru',
            },
            location: {
              brewery_city: 'Мышецкое',
              brewery_state: 'Московская область',
              lat: 56.0404015,
              lng: 37.3432007,
            },
            brewery_active: 1,
          },
        },
        {
          first_checkin_id: 1098432905,
          first_created_at: 'Sat, 13 Nov 2021 22:18:13 +0300',
          recent_checkin_id: 1098432905,
          recent_created_at: 'Sat, 13 Nov 2021 22:18:13 +0300',
          recent_created_at_timezone: '3',
          rating_score: 3.5,
          user_auth_rating_score: 0,
          first_had: 'Sat, 13 Nov 2021 22:18:13 +0300',
          count: 1,
          beer: {
            bid: 4569403,
            beer_name: 'A MOUSE CALLED LAVANDA',
            beer_label:
              'https://untappd.akamaized.net/site/beer_logos/beer-4569403_29e6a_sm.jpeg',
            beer_abv: 5.9,
            beer_ibu: 9,
            beer_slug: 'rising-moon-brewery-a-mouse-called-lavanda',
            beer_style: 'Sour - Other',
            beer_description:
              'Наша интерпретация кофейного напитка РАФ с добавлением лаванды. Кофейные ноты передал солод, а добавив лаванду пиво стало похоже на популярный напиток из кофеен. Этикетка создана в пародию на знаменитый фильм.',
            created_at: 'Fri, 29 Oct 2021 08:12:21 +0000',
            rating_score: 3.71951,
            rating_count: 41,
            has_had: false,
          },
          brewery: {
            brewery_id: 337614,
            brewery_name: 'Rising Moon Brewery',
            brewery_slug: 'rising-moon-brewery',
            brewery_page_url: '/RMBrewery',
            brewery_type: 'Micro Brewery',
            brewery_label:
              'https://untappd.akamaized.net/site/brewery_logos/brewery-337614_a4dd4.jpeg',
            country_name: 'Russia',
            contact: {
              twitter: '',
              facebook: '',
              instagram: 'risingmoonbrewery.ru',
              url: 'http://www.rmbrew.ru',
            },
            location: {
              brewery_city: 'Мышецкое',
              brewery_state: 'Московская область',
              lat: 56.0404015,
              lng: 37.3432007,
            },
            brewery_active: 1,
          },
        },
        {
          first_checkin_id: 1098418037,
          first_created_at: 'Sat, 13 Nov 2021 22:04:04 +0300',
          recent_checkin_id: 1098418037,
          recent_created_at: 'Sat, 13 Nov 2021 22:04:04 +0300',
          recent_created_at_timezone: '3',
          rating_score: 3.75,
          user_auth_rating_score: 0,
          first_had: 'Sat, 13 Nov 2021 22:04:04 +0300',
          count: 1,
          beer: {
            bid: 4213652,
            beer_name: 'Pramień: Batch #01',
            beer_label:
              'https://untappd.akamaized.net/site/beer_logos/beer-4213652_3cef0_sm.jpeg',
            beer_abv: 6.5,
            beer_ibu: 0,
            beer_slug: 'malanka-pramien-batch-01',
            beer_style: 'Farmhouse Ale - Saison',
            beer_description:
              'Saison is the style hard to define. The only thing we can say for sure is that it originated in Belgium and its character is largely defined by the yeast. The dry and phenolic profile of this beer twists beautifully with Brettanomyces. In “Pramień”, we used a blend of saison yeast and Brettanomyces, gave the beer more than half a year to form a taste and round up the palate, then sent it to the bottles for a few more months to referment and get those millions of tiny bubbles. This is a comforting beam of light during troubled times, and we hope you enjoy it as much as we do.',
            created_at: 'Wed, 10 Mar 2021 09:43:14 +0000',
            rating_score: 4.11126,
            rating_count: 262,
            has_had: false,
          },
          brewery: {
            brewery_id: 431182,
            brewery_name: 'Malanka',
            brewery_slug: 'malanka',
            brewery_page_url: '/Malanka',
            brewery_type: 'Nano Brewery',
            brewery_label:
              'https://untappd.akamaized.net/site/brewery_logos/brewery-431182_d709f.jpeg',
            country_name: 'Belarus',
            contact: {
              twitter: 'brovar_malanka',
              facebook: 'https://www.facebook.com/brovar.malanka/',
              instagram: 'brovar.malanka',
              url: 'https://malanka.beer',
            },
            location: {
              brewery_city: 'Minsk',
              brewery_state: 'Minsk',
              lat: 53.9006004,
              lng: 27.559,
            },
            brewery_active: 1,
          },
        },
        {
          first_checkin_id: 1098349743,
          first_created_at: 'Sat, 13 Nov 2021 20:53:01 +0300',
          recent_checkin_id: 1098349743,
          recent_created_at: 'Sat, 13 Nov 2021 20:53:01 +0300',
          recent_created_at_timezone: '3',
          rating_score: 4,
          user_auth_rating_score: 0,
          first_had: 'Sat, 13 Nov 2021 20:53:01 +0300',
          count: 1,
          beer: {
            bid: 4586987,
            beer_name: 'Полуночное солнце',
            beer_label:
              'https://untappd.akamaized.net/site/assets/images/temp/badge-beer-default.png',
            beer_abv: 11,
            beer_ibu: 19,
            beer_slug: 'tulpa-brewery-polunochnoe-solnce',
            beer_style: 'Strong Ale - Other',
            beer_description: 'Крепкий, теплый, карамельный на воссах.',
            created_at: 'Wed, 10 Nov 2021 06:37:32 +0000',
            rating_score: 3.69194,
            rating_count: 62,
            has_had: false,
          },
          brewery: {
            brewery_id: 485957,
            brewery_name: 'Tulpa brewery',
            brewery_slug: 'tulpa-brewery',
            brewery_page_url: '/Tulpabrewery',
            brewery_type: 'Micro Brewery',
            brewery_label:
              'https://untappd.akamaized.net/site/brewery_logos/brewery-485957_2c504.jpeg',
            country_name: 'Russia',
            contact: {
              twitter: '',
              facebook: '',
              instagram: 'Tulpabrewery',
              url: '',
            },
            location: {
              brewery_city: '',
              brewery_state: '',
              lat: 0,
              lng: 0,
            },
            brewery_active: 1,
          },
        },
        {
          first_checkin_id: 1098327082,
          first_created_at: 'Sat, 13 Nov 2021 20:27:10 +0300',
          recent_checkin_id: 1098327082,
          recent_created_at: 'Sat, 13 Nov 2021 20:27:10 +0300',
          recent_created_at_timezone: '3',
          rating_score: 4.25,
          user_auth_rating_score: 0,
          first_had: 'Sat, 13 Nov 2021 20:27:10 +0300',
          count: 1,
          beer: {
            bid: 4380992,
            beer_name: 'Lobotomy PX',
            beer_label:
              'https://untappd.akamaized.net/site/beer_logos/beer-4380992_21e8f_sm.jpeg',
            beer_abv: 13.5,
            beer_ibu: 50,
            beer_slug: 'af-brew-lobotomy-px',
            beer_style: 'Stout - Imperial / Double',
            beer_description: 'Welcome to 2021, the Year of Lobotomy PX',
            created_at: 'Sat, 26 Jun 2021 09:19:19 +0000',
            rating_score: 4.27123,
            rating_count: 2852,
            has_had: false,
          },
          brewery: {
            brewery_id: 38368,
            brewery_name: 'AF Brew',
            brewery_slug: 'af-brew',
            brewery_page_url: '/AntiFactory',
            brewery_type: 'Micro Brewery',
            brewery_label:
              'https://untappd.akamaized.net/site/brewery_logos/brewery-38368_abe05.jpeg',
            country_name: 'Russia',
            contact: {
              twitter: 'afbrew',
              facebook: 'https://www.facebook.com/AF.CraftBeer',
              instagram: 'afbrew',
              url: 'https://afbrew.co/',
            },
            location: {
              brewery_city: 'Saint Petersburg',
              brewery_state: 'Санкт-Петербург',
              lat: 59.9107018,
              lng: 30.2660007,
            },
            brewery_active: 1,
          },
        },
        {
          first_checkin_id: 1098326164,
          first_created_at: 'Sat, 13 Nov 2021 20:26:04 +0300',
          recent_checkin_id: 1098326164,
          recent_created_at: 'Sat, 13 Nov 2021 20:26:04 +0300',
          recent_created_at_timezone: '3',
          rating_score: 4,
          user_auth_rating_score: 0,
          first_had: 'Sat, 13 Nov 2021 20:26:04 +0300',
          count: 1,
          beer: {
            bid: 4533536,
            beer_name: 'Bahna: Extra Peated',
            beer_label:
              'https://untappd.akamaized.net/site/beer_logos/beer-4533536_72420_sm.jpeg',
            beer_abv: 12,
            beer_ibu: 0,
            beer_slug: 'malanka-bahna-extra-peated',
            beer_style: 'Stout - Imperial / Double',
            beer_description:
              "Smoked Imperial Stout with Ultra Peated Malt. Collaboration with Jungle Brewery.\r\n\r\nAlmost a year and a half ago to this day, we released our first collaboration with our friends at Jungle Brewery - Bahna Smoked Imperial Stout. Since then, we have brewed several more beers together, some of which will be released later. But now is a perfect moment to release Bahna again, only this time with an improved recipe. It seemed to us that there is never enough peated flavour - we are from Belarus, for hell's sake! - so this time we used the most smoked malt we could find. Ultra Peated malt from Scottish producer Crisp Malt has a phenol contents of up to 80 ppm and is used in the production of local distillates. Its smoky profile, with characteristic aromas of rubber, iodine and creosote, is familiar to islay whiskey lovers. With its help, we managed to achieve the most smoky smell and taste. Together with a thick and heavy body, they create a memorable drink that will appeal not only to lovers of imperial stouts, but also to fans of travelling by train and drinking Scotch whiskey.",
            created_at: 'Sun, 03 Oct 2021 19:51:26 +0000',
            rating_score: 4.40179,
            rating_count: 308,
            has_had: false,
          },
          brewery: {
            brewery_id: 431182,
            brewery_name: 'Malanka',
            brewery_slug: 'malanka',
            brewery_page_url: '/Malanka',
            brewery_type: 'Nano Brewery',
            brewery_label:
              'https://untappd.akamaized.net/site/brewery_logos/brewery-431182_d709f.jpeg',
            country_name: 'Belarus',
            contact: {
              twitter: 'brovar_malanka',
              facebook: 'https://www.facebook.com/brovar.malanka/',
              instagram: 'brovar.malanka',
              url: 'https://malanka.beer',
            },
            location: {
              brewery_city: 'Minsk',
              brewery_state: 'Minsk',
              lat: 53.9006004,
              lng: 27.559,
            },
            brewery_active: 1,
          },
        },
        {
          first_checkin_id: 1098321306,
          first_created_at: 'Sat, 13 Nov 2021 20:20:22 +0300',
          recent_checkin_id: 1098321306,
          recent_created_at: 'Sat, 13 Nov 2021 20:20:22 +0300',
          recent_created_at_timezone: '3',
          rating_score: 4.25,
          user_auth_rating_score: 0,
          first_had: 'Sat, 13 Nov 2021 20:20:22 +0300',
          count: 1,
          beer: {
            bid: 4246255,
            beer_name: 'Apricot Wild Mead',
            beer_label:
              'https://untappd.akamaized.net/site/beer_logos/beer-4246255_ca1e9_sm.jpeg',
            beer_abv: 12,
            beer_ibu: 0,
            beer_slug: 'steppe-and-wind-meadery-step-i-veter-apricot-wild-mead',
            beer_style: 'Mead - Melomel',
            beer_description:
              'Липовый мёд, сброженный блендом диких дрожжей с дубовой щепой и абрикосами на протяжении 8 месяцев.',
            created_at: 'Thu, 01 Apr 2021 07:01:15 +0000',
            rating_score: 4.28703,
            rating_count: 609,
            has_had: false,
          },
          brewery: {
            brewery_id: 236249,
            brewery_name: 'Steppe & Wind Meadery (Степь и Ветер)',
            brewery_slug: 'steppe-wind-meadery-step-i-veter',
            brewery_page_url: '/SteppeNwind',
            brewery_type: 'Meadery',
            brewery_label:
              'https://untappd.akamaized.net/site/brewery_logos/brewery-236249_1e281.jpeg',
            country_name: 'Russia',
            contact: {
              twitter: '',
              facebook: '',
              instagram: 'stepiveter',
              url: 'https://vk.com/stepiveter',
            },
            location: {
              brewery_city: 'Orenburg',
              brewery_state: 'Оренбургская область',
              lat: 51.7641983,
              lng: 55.1021996,
            },
            brewery_active: 1,
          },
        },
        {
          first_checkin_id: 1098319159,
          first_created_at: 'Sat, 13 Nov 2021 20:17:45 +0300',
          recent_checkin_id: 1098319159,
          recent_created_at: 'Sat, 13 Nov 2021 20:17:45 +0300',
          recent_created_at_timezone: '3',
          rating_score: 4,
          user_auth_rating_score: 0,
          first_had: 'Sat, 13 Nov 2021 20:17:45 +0300',
          count: 1,
          beer: {
            bid: 4506472,
            beer_name: 'Estasi Di Santa Teresa',
            beer_label:
              'https://untappd.akamaized.net/site/beer_logos/beer-4506472_22c07_sm.jpeg',
            beer_abv: 17,
            beer_ibu: 0,
            beer_slug: 'api-del-bernini-estasi-di-santa-teresa',
            beer_style: 'Mead - Melomel',
            beer_description: 'Сranberry & Blackberry',
            created_at: 'Thu, 16 Sep 2021 13:04:06 +0000',
            rating_score: 4.16803,
            rating_count: 61,
            has_had: false,
          },
          brewery: {
            brewery_id: 508120,
            brewery_name: 'Api Del Bernini',
            brewery_slug: 'api-del-bernini',
            brewery_page_url: '/ApiDelBernini',
            brewery_type: 'Meadery',
            brewery_label:
              'https://untappd.akamaized.net/site/brewery_logos/brewery-508120_b2bea.jpeg',
            country_name: 'Russia',
            contact: {
              twitter: '',
              facebook: 'https://www.facebook.com/apideibernini',
              instagram: 'apidelbernini',
              url: '',
            },
            location: {
              brewery_city: '',
              brewery_state: '',
              lat: 0,
              lng: 0,
            },
            brewery_active: 1,
          },
        },
        {
          first_checkin_id: 1098300599,
          first_created_at: 'Sat, 13 Nov 2021 19:52:43 +0300',
          recent_checkin_id: 1098300599,
          recent_created_at: 'Sat, 13 Nov 2021 19:52:43 +0300',
          recent_created_at_timezone: '3',
          rating_score: 4,
          user_auth_rating_score: 0,
          first_had: 'Sat, 13 Nov 2021 19:52:43 +0300',
          count: 1,
          beer: {
            bid: 4590102,
            beer_name: 'Meadwest: Five Berries',
            beer_label:
              'https://untappd.akamaized.net/site/beer_logos/beer-4590102_b8e50_sm.jpeg',
            beer_abv: 13.5,
            beer_ibu: 0,
            beer_slug: 'zagovor-brewery-meadwest-five-berries',
            beer_style: 'Mead - Melomel',
            beer_description:
              'Melomel Mead with five noble berries: black currant, blueberry, chokeberry, raspberry & blackberry.',
            created_at: 'Fri, 12 Nov 2021 10:47:19 +0000',
            rating_score: 4.06156,
            rating_count: 147,
            has_had: false,
          },
          brewery: {
            brewery_id: 135208,
            brewery_name: 'Zagovor Brewery',
            brewery_slug: 'zagovor-brewery',
            brewery_page_url: '/ZagovorBrewery',
            brewery_type: 'Micro Brewery',
            brewery_label:
              'https://untappd.akamaized.net/site/brewery_logos/brewery-135208_51cc2.jpeg',
            country_name: 'Russia',
            contact: {
              twitter: '',
              facebook: 'http://www.facebook.com/zagovorbrewery',
              instagram: 'zagovorbrewery',
              url: 'http://zagovorbrewery.com',
            },
            location: {
              brewery_city: 'Moscow',
              brewery_state: 'Москва',
              lat: 55.7513008,
              lng: 37.6074982,
            },
            brewery_active: 1,
          },
        },
        {
          first_checkin_id: 1098287634,
          first_created_at: 'Sat, 13 Nov 2021 19:33:08 +0300',
          recent_checkin_id: 1098287634,
          recent_created_at: 'Sat, 13 Nov 2021 19:33:08 +0300',
          recent_created_at_timezone: '3',
          rating_score: 3.75,
          user_auth_rating_score: 0,
          first_had: 'Sat, 13 Nov 2021 19:33:08 +0300',
          count: 1,
          beer: {
            bid: 4416483,
            beer_name: 'Flemish Red Ale 2018',
            beer_label:
              'https://untappd.akamaized.net/site/beer_logos/beer-4416483_2a6b6_sm.jpeg',
            beer_abv: 7,
            beer_ibu: 20,
            beer_slug: 'zavod-flemish-red-ale-2018',
            beer_style: 'Sour - Flanders Red Ale',
            beer_description:
              'Лимитированная серия, заложенная в дубовые бочки осенью 2018 года.',
            created_at: 'Sat, 17 Jul 2021 20:16:11 +0000',
            rating_score: 4.00138,
            rating_count: 289,
            has_had: false,
          },
          brewery: {
            brewery_id: 271235,
            brewery_name: 'Zavod',
            brewery_slug: 'zavod',
            brewery_page_url: '/Zavodbrewery',
            brewery_type: 'Micro Brewery',
            brewery_label:
              'https://untappd.akamaized.net/site/brewery_logos/brewery-271235_29a29.jpeg',
            country_name: 'Russia',
            contact: {
              twitter: '',
              facebook: 'https://www.facebook.com/beerzavod/',
              instagram: 'beerzavod',
              url: 'http://beerzavod.ru',
            },
            location: {
              brewery_city: 'Khimki',
              brewery_state: 'Московская область',
              lat: 55.9101982,
              lng: 37.4342995,
            },
            brewery_active: 1,
          },
        },
        {
          first_checkin_id: 1098284561,
          first_created_at: 'Sat, 13 Nov 2021 19:28:06 +0300',
          recent_checkin_id: 1098284561,
          recent_created_at: 'Sat, 13 Nov 2021 19:28:06 +0300',
          recent_created_at_timezone: '3',
          rating_score: 4.25,
          user_auth_rating_score: 0,
          first_had: 'Sat, 13 Nov 2021 19:28:06 +0300',
          count: 1,
          beer: {
            bid: 4550939,
            beer_name: 'Lost Land (BA Cognac)',
            beer_label:
              'https://untappd.akamaized.net/site/beer_logos/beer-4550939_d5b4f_sm.jpeg',
            beer_abv: 9,
            beer_ibu: 0,
            beer_slug: 'big-village-brewery-lost-land-ba-cognac',
            beer_style: 'Belgian Strong Dark Ale',
            beer_description:
              'Бельгийский крепкий темный эль ферментированный блендом сахаромицет и бреттаномицет, выдержанный 2 года в коньячной бочке с добавление вишни.',
            created_at: 'Sat, 16 Oct 2021 10:32:08 +0000',
            rating_score: 4.35985,
            rating_count: 335,
            has_had: false,
          },
          brewery: {
            brewery_id: 210563,
            brewery_name: 'Big Village Brewery',
            brewery_slug: 'big-village-brewery',
            brewery_page_url: '/BVBrewery',
            brewery_type: 'Micro Brewery',
            brewery_label:
              'https://untappd.akamaized.net/site/brewery_logos/brewery-210563_22887.jpeg',
            country_name: 'Russia',
            contact: {
              twitter: '',
              facebook: 'https://facebook.com/bigvillagebrewery',
              instagram: 'big_village_brew',
              url: 'https://vk.com/bigvillage',
            },
            location: {
              brewery_city: 'Krasnodar',
              brewery_state: 'Краснодарский край',
              lat: 45.0261993,
              lng: 39.0460014,
            },
            brewery_active: 1,
          },
        },
        {
          first_checkin_id: 1098275406,
          first_created_at: 'Sat, 13 Nov 2021 19:13:26 +0300',
          recent_checkin_id: 1098275406,
          recent_created_at: 'Sat, 13 Nov 2021 19:13:26 +0300',
          recent_created_at_timezone: '3',
          rating_score: 3.75,
          user_auth_rating_score: 0,
          first_had: 'Sat, 13 Nov 2021 19:13:26 +0300',
          count: 1,
          beer: {
            bid: 4054559,
            beer_name: 'Kingston Black S.V.C (American Oak Cask Wild Ferment)',
            beer_label:
              'https://untappd.akamaized.net/site/beer_logos/beer-4054559_debea_sm.jpeg',
            beer_abv: 8,
            beer_ibu: 0,
            beer_slug:
              'ross-on-wye-cider-and-perry-kingston-black-s-v-c-american-oak-cask-wild-ferment',
            beer_style: 'Cider - Dry',
            beer_description:
              'Kingston Black is a revered bittersharp apple that originated in Somerset in the 1800s. Unique for having both luscious acidity and prominent tannins, it became widely planted, despite the tree itself being very frustrating to grow. Such was the quality of the cider, that many of us persevered, and here we have been rewarded.\r\n\r\nFrom a trees grown with care in the Ross orchards, this was fermented in fresh Kentucky oak. The result is a cider of vivid juiciness,  aromatic vanilla, big ripe red apples, and a gentle tannic finish.',
            created_at: 'Sat, 14 Nov 2020 20:06:34 +0000',
            rating_score: 4.00467,
            rating_count: 75,
            has_had: false,
          },
          brewery: {
            brewery_id: 12570,
            brewery_name: 'Ross on Wye Cider & Perry',
            brewery_slug: 'ross-on-wye-cider-perry',
            brewery_page_url: '/RossCider',
            brewery_type: 'Cidery',
            brewery_label:
              'https://untappd.akamaized.net/site/brewery_logos/brewery-12570_6db70.jpeg',
            country_name: 'England',
            contact: {
              twitter: 'rosscider',
              facebook: 'http://www.facebook.com/rosscider',
              instagram: 'rosscider',
              url: 'http://www.rosscider.com/',
            },
            location: {
              brewery_city: 'Ross-on-Wye',
              brewery_state: 'Herefordshire',
              lat: 51.9217987,
              lng: -2.62795,
            },
            brewery_active: 1,
          },
        },
        {
          first_checkin_id: 1093735135,
          first_created_at: 'Sat, 30 Oct 2021 22:21:02 +0300',
          recent_checkin_id: 1093735135,
          recent_created_at: 'Sat, 30 Oct 2021 22:21:02 +0300',
          recent_created_at_timezone: '3',
          rating_score: 3.75,
          user_auth_rating_score: 0,
          first_had: 'Sat, 30 Oct 2021 22:21:02 +0300',
          count: 1,
          beer: {
            bid: 999698,
            beer_name: 'Sidra Natural M. Busto',
            beer_label:
              'https://untappd.akamaized.net/site/assets/images/temp/badge-beer-default.png',
            beer_abv: 6,
            beer_ibu: 0,
            beer_slug: 'sidra-mayador-sidra-natural-m-busto',
            beer_style: 'Cider - Traditional / Apfelwein',
            beer_description:
              'Manzanas asturianas de variedades amargas y ácidas. Fermentación en toneles\r\nde castaño',
            created_at: 'Fri, 06 Mar 2015 07:35:09 +0000',
            rating_score: 3.81476,
            rating_count: 376,
            has_had: false,
          },
          brewery: {
            brewery_id: 91882,
            brewery_name: 'Sidra Mayador',
            brewery_slug: 'sidra-mayador',
            brewery_page_url: '/SidraMayador',
            brewery_type: 'Cidery',
            brewery_label:
              'https://untappd.akamaized.net/site/brewery_logos/brewery-91882_134ca.jpeg',
            country_name: 'Spain',
            contact: {
              twitter: 'sidraMayador',
              facebook: 'https://www.facebook.com/sidramayadorcider',
              instagram: 'sidramayadorcider',
              url: 'http://www.mayador.com/',
            },
            location: {
              brewery_city: 'La Rasa',
              brewery_state: 'Asturias / Asturies',
              lat: 43.5181007,
              lng: -5.6240301,
            },
            brewery_active: 1,
          },
        },
        {
          first_checkin_id: 1091877096,
          first_created_at: 'Sun, 24 Oct 2021 21:22:06 +0300',
          recent_checkin_id: 1091877096,
          recent_created_at: 'Sun, 24 Oct 2021 21:22:06 +0300',
          recent_created_at_timezone: '3',
          rating_score: 4,
          user_auth_rating_score: 0,
          first_had: 'Sun, 24 Oct 2021 21:22:06 +0300',
          count: 1,
          beer: {
            bid: 4555215,
            beer_name: 'Sarcasmotron #4',
            beer_label:
              'https://untappd.akamaized.net/site/assets/images/temp/badge-beer-default.png',
            beer_abv: 15,
            beer_ibu: 0,
            beer_slug: 'share-house-sarcasmotron-4',
            beer_style: 'Mead - Other',
            beer_description:
              'Продолжаем Эру Сарказмотрона! Хрустальная мечта уставшего биргика сверкающая на стойке в том самом барчике, где делят бутылки, горести и радости.\r\n\r\nВерсия четвёртая: крепкий приводящий в чувство мид с лимонами, апельсинами и мятой. ',
            created_at: 'Tue, 19 Oct 2021 12:52:09 +0000',
            rating_score: 3.91081,
            rating_count: 37,
            has_had: false,
          },
          brewery: {
            brewery_id: 424520,
            brewery_name: 'Share House',
            brewery_slug: 'share-house',
            brewery_page_url: '/Share-House',
            brewery_type: 'Brew Pub',
            brewery_label:
              'https://untappd.akamaized.net/site/brewery_logos/brewery-424520_1b13b.jpeg',
            country_name: 'Russia',
            contact: {
              twitter: '',
              facebook: 'https://www.facebook.com/sharehousebar/',
              instagram: 'sharehousebar',
              url: '',
            },
            location: {
              brewery_city: 'Moscow',
              brewery_state: 'Москва',
              lat: 55.7706985,
              lng: 37.5969009,
            },
            brewery_active: 1,
          },
        },
      ],
      sort_english: 'Date (New to Old)',
      sort_name: 'Date (New to Old)',
    },
    sort_key: 'date',
    sort_name: 'Date (New to Old)',
    pagination: {
      next_url: 'https://api.untappd.com/v4/user/beers/beaverd2?offset=25',
      offset: 25,
      max_id: false,
    },
  },
};

export const user = {
  meta: {
    code: 200,
    response_time: {
      time: 0.04,
      measure: 'seconds',
    },
    init_time: {
      time: 0,
      measure: 'seconds',
    },
  },
  notifications: [],
  response: {
    user: {
      uid: 6786800,
      id: 6786800,
      user_name: 'beaverd2',
      first_name: 'Oleg',
      last_name: 'Beaver',
      user_avatar:
        'https://untappd.akamaized.net/profile/c5c0b2c172e7549e3c7e50eb153aec6f_100x100.jpg',
      user_avatar_hd:
        'https://untappd.akamaized.net/profile/c5c0b2c172e7549e3c7e50eb153aec6f_300x300.jpg',
      user_cover_photo:
        'https://untappd.akamaized.net/site/assets/v3/images/cover_default.jpg',
      user_cover_photo_offset: 0,
      is_private: 0,
      rating_bump: 0,
      location: '',
      url: '',
      bio: 'Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet ',
      is_supporter: 0,
      is_moderator: 0,
      relationship: null,
      block_status: 'none',
      mute_status: 'unmute',
      untappd_url: 'http://untappd.com/user/beaverd2',
      account_type: 'user',
      stats: {
        total_badges: 1342,
        total_friends: 13,
        total_checkins: 982,
        total_beers: 871,
        total_created_beers: 0,
        total_followings: 0,
        total_photos: 299,
      },
      contact: [],
      date_joined: 'Fri, 07 Jun 2019 22:28:46 +0000',
      settings: [],
      subscribe: {
        is_subscribed: 0,
        subscribe_type: 'none',
      },
    },
  },
};
